title: Popagandhi
description: Between long form cycling and tech

url: http://popagandhi.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: skinnylatte
   twitter: skinnylatte
   facebook: skinnylatte
   email: skinnylatte@gmail.com

# google_analytics: "UA-58263416-1"

theme: jekyll-theme-minimal