# Site settings
title: 'Popagandhi'
email: 'skinnylatte@gmail.com'
description: 'Between long form cycling and tech'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://popagandhi.com'
enable_retina: false
markdown: kramdown
highlighter: rouge
paginate: 6
permalink: :title
nav_list:
  Home : ['Home', '/']
  About : ['About', '/about']
  Contact : ['Contact', '/contact']
  Author : ['Author', '/author/adrianna']
single_footer: 'Copyright &copy; 2017 69signals'
footer_links:
  About: ['About', '/about']
  Writer: ['Contact', '/contact']
social_links:
  Email: ['Email', 'mailto:skinnylatte@gmail.com', 'fa-envelope-o']
  Twitter: ['Twitter', 'https://twitter.com/skinnylatte', 'fa-twitter']
  Facebook: ['Facebook', 'https://www.facebook.com/adrianna.tan', 'fa-facebook']
  Google: ['Instagram', 'https://instagram.com/skinnylatte', 'fa-instagram']
  Instagram: ['Github', 'https://github.com/skinnylatte', 'fa-github-alt']
sidebar:
  author_name: 'Adrianna Tan'
  author_about: ['I’m a startup founder from Singapore who has spent considerable amounts of time working and living across India, Indonesia, Malaysia, Myanmar and Bangladesh, with short stints in America, the UK and Hungary.']
  author_avatar: 'adrianna'
  author_location: 'Indonesia'
jekyll-archives:
  enabled:
    - year
    - month
    - day
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
gems:
  - jekyll-paginate
##  - jekyll-archives